language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

# workarround to successful build a forked go package
#before_install:
#  - mkdir -p $HOME/gopath/src/github.com/fritzing
#  - ln -s -T ${TRAVIS_BUILD_DIR} $HOME/gopath/src/github.com/fritzing/fzp
#  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/fritzing/fzp

install:
  - go get ./...

  script:
    - cd bin/fzp && make test
    - cd src/go && make test
